language: php
php:
  - 7.2
  - 7.3
  - nightly
  
matrix:
  allow_failures:
  - php: nightly

install:
 - composer self-update
 - composer install --no-interaction --dev
before_script:
  - mkdir -p build/
  - mkdir -p build/logs
script:
 - phpunit
after_script:
 - php vendor/bin/coveralls -v
 - php vendor/bin/codacycoverage clover build/logs/clover.xml
